const QUESTIONS_BANK = {

  football: [
    { type: "multiple_choice", question: "כמה פעמים זכה ליאו מסי בכדור הזהב?", options: ["6", "7", "8", "5"], answer: "8", topic: "football" },
    { type: "true_false", question: "ליאו מסי זכה עם ארגנטינה בגביע העולם 2022 בקטאר", options: ["נכון", "לא נכון"], answer: "נכון", topic: "football" },
    { type: "multiple_choice", question: "מי הבקיע האט-טריק בגמר גביע העולם 2022?", options: ["קיליאן מבאפה", "ליאו מסי", "אוליבייה ז'ירו", "אנטואן גריזמן"], answer: "קיליאן מבאפה", topic: "football" },
    { type: "multiple_choice", question: "איזו נבחרת זכתה בגביע העולם 2018?", options: ["ברזיל", "ספרד", "צרפת", "גרמניה"], answer: "צרפת", topic: "football" },
    { type: "multiple_choice", question: "איזו נבחרת זכתה בגביע העולם 2014?", options: ["ברזיל", "ארגנטינה", "גרמניה", "צרפת"], answer: "גרמניה", topic: "football" },
    { type: "true_false", question: "ריאל מדריד זכתה בליגת האלופות שלוש פעמים ברצף בין 2016-2018", options: ["נכון", "לא נכון"], answer: "נכון", topic: "football" },
    { type: "multiple_choice", question: "באיזה מועדון משחק קריסטיאנו רונאלדו כיום?", options: ["ריאל מדריד", "אל-נאסר", "מנצ'סטר יונייטד", "יובנטוס"], answer: "אל-נאסר", topic: "football" },
    { type: "multiple_choice", question: "מי הכדורגלן עם הכי הרבה שערים בהיסטוריית גביעי העולם?", options: ["ליאו מסי", "רונאלדו הברזילאי", "מירוסלב קלוזה", "גרד מולר"], answer: "מירוסלב קלוזה", topic: "football" },
    { type: "multiple_choice", question: "ארלינג הלאנד משחק באיזה מועדון?", options: ["ריאל מדריד", "ברצלונה", "מנצ'סטר סיטי", "בוורוסיה דורטמונד"], answer: "מנצ'סטר סיטי", topic: "football" },
    { type: "true_false", question: "מנצ'סטר סיטי זכתה בליגת האלופות 2023", options: ["נכון", "לא נכון"], answer: "נכון", topic: "football" },
    { type: "multiple_choice", question: "באיזו מדינה התקיים גביע העולם 2022?", options: ["איחוד האמירויות", "ערב הסעודית", "קטאר", "בחריין"], answer: "קטאר", topic: "football" },
    { type: "true_false", question: "גביע העולם 2026 יתקיים בארה\"ב, מקסיקו וקנדה", options: ["נכון", "לא נכון"], answer: "נכון", topic: "football" },
    { type: "open", question: "מהו שם הטורניר האירופאי שהפועל באר שבע הגיעה לשלב הבתים שלו לראשונה בהיסטוריה ב-2016?", answer: "ליגת אירופה (UEFA Europa League)", topic: "football" },
    { type: "multiple_choice", question: "כמה אליפויות ליגת העל רצופות זכתה הפועל באר שבע בין 2015-2019?", options: ["3", "4", "5", "2"], answer: "4", topic: "football" },
    { type: "true_false", question: "הפועל באר שבע זכתה ב-6 אליפויות ליגת העל בין השנים 2015-2022", options: ["נכון", "לא נכון"], answer: "נכון", topic: "football" },
    { type: "multiple_choice", question: "מי הוא שחקן הכנף הברזילאי הזוהר של ריאל מדריד?", options: ["נמאר", "ויניסיוס ג'וניור", "רודריגו", "רפיניה"], answer: "ויניסיוס ג'וניור", topic: "football" },
    { type: "multiple_choice", question: "ליאו מסי משחק כיום באיזה מועדון?", options: ["פריז סן-ז'רמן", "ברצלונה", "אינטר מיאמי", "מנצ'סטר סיטי"], answer: "אינטר מיאמי", topic: "football" },
    { type: "true_false", question: "קיליאן מבאפה עבר לריאל מדריד ב-2024", options: ["נכון", "לא נכון"], answer: "נכון", topic: "football" },
    { type: "multiple_choice", question: "מי זכה בכדור הזהב 2024?", options: ["קיליאן מבאפה", "ויניסיוס ג'וניור", "רודרי", "ארלינג הלאנד"], answer: "רודרי", topic: "football" },
    { type: "open", question: "מי ניצח במשחק גמר גביע העולם 2022 אחרי הארכות ועונשין?", answer: "ארגנטינה (ניצחה את צרפת בעונשין)", topic: "football" },
    { type: "multiple_choice", question: "איזה קבוצה זכתה בליגת האלופות 2024?", options: ["מנצ'סטר סיטי", "ריאל מדריד", "בוורן מינכן", "פריז סן-ז'רמן"], answer: "ריאל מדריד", topic: "football" },
    { type: "true_false", question: "נבחרת ישראל השתתפה ביורו 2024 בגרמניה", options: ["נכון", "לא נכון"], answer: "נכון", topic: "football" },
    { type: "multiple_choice", question: "כמה קבוצות מתחרות בגביע העולם החל מ-2026?", options: ["32", "36", "48", "64"], answer: "48", topic: "football" },
    { type: "open", question: "מהי ליגת הכדורגל המקצועית הראשית בספרד?", answer: "לה ליגה (La Liga)", topic: "football" },
    { type: "multiple_choice", question: "מי הוא שחקן הכדורגל עם הציוצר הכי גבוה בהיסטוריה בלירות שטרלינג?", options: ["ג'ק גרילי'ש", "ניימאר", "קיליאן מבאפה", "פיל פודן"], answer: "ניימאר", topic: "football" },
  ],

  music: [
    { type: "multiple_choice", question: "מאיזה אלבום של טיילור סוויפט השיר 'Anti-Hero'?", options: ["Lover", "Reputation", "Midnights", "Folklore"], answer: "Midnights", topic: "music" },
    { type: "true_false", question: "השיר 'Shake It Off' של טיילור סוויפט הוא מהאלבום '1989'", options: ["נכון", "לא נכון"], answer: "נכון", topic: "music" },
    { type: "multiple_choice", question: "מהו שם הסיבוב הגדול של טיילור סוויפט ב-2023-2024?", options: ["Reputation Stadium Tour", "The Eras Tour", "Fearless Tour", "1989 World Tour"], answer: "The Eras Tour", topic: "music" },
    { type: "multiple_choice", question: "מהו האלבום הראשון של טיילור סוויפט?", options: ["Fearless", "Speak Now", "Taylor Swift", "Red"], answer: "Taylor Swift", topic: "music" },
    { type: "open", question: "מאיזה אלבום השיר 'Cruel Summer' של טיילור סוויפט?", answer: "Lover (2019)", topic: "music" },
    { type: "multiple_choice", question: "מהו הסינגל הראשון של אוליביה רודריגו שהפך להיט עולמי ב-2021?", options: ["good 4 u", "drivers license", "deja vu", "brutal"], answer: "drivers license", topic: "music" },
    { type: "multiple_choice", question: "מהו האלבום הראשון של אוליביה רודריגו?", options: ["GUTS", "SOUR", "Vampire", "Brutal"], answer: "SOUR", topic: "music" },
    { type: "true_false", question: "השיר 'vampire' של אוליביה רודריגו הוא מהאלבום GUTS", options: ["נכון", "לא נכון"], answer: "נכון", topic: "music" },
    { type: "multiple_choice", question: "מאיזה אלבום של סברינה קרפנטר השיר 'Espresso'?", options: ["emails i can't send", "Short n' Sweet", "Evolution", "singular"], answer: "Short n' Sweet", topic: "music" },
    { type: "true_false", question: "BTS היא להקת קיי-פופ קוריאנית", options: ["נכון", "לא נכון"], answer: "נכון", topic: "music" },
    { type: "multiple_choice", question: "מי שרה את השיר 'bad guy'?", options: ["אריאנה גראנדה", "דואה ליפה", "בילי אייליש", "הלסי"], answer: "בילי אייליש", topic: "music" },
    { type: "multiple_choice", question: "לאיזה סרט בונד כתבה בילי אייליש את שיר הנושא?", options: ["Skyfall", "Spectre", "Casino Royale", "No Time to Die"], answer: "No Time to Die", topic: "music" },
    { type: "open", question: "מי שרה את השיר 'Flowers' שיצא ב-2023 ביום ההולדת של בעלה לשעבר?", answer: "מיילי סיירוס (Miley Cyrus)", topic: "music" },
    { type: "multiple_choice", question: "מי שרה את השיר 'As It Was' (2022)?", options: ["הארי סטיילס", "נייל יאנג", "אד שירן", "The Weeknd"], answer: "הארי סטיילס", topic: "music" },
    { type: "multiple_choice", question: "מאיזה אלבום של דואה ליפה השיר 'Levitating'?", options: ["Dua Lipa", "Future Nostalgia", "Radical Optimism", "Club Future Nostalgia"], answer: "Future Nostalgia", topic: "music" },
    { type: "true_false", question: "הארי סטיילס היה חבר בלהקת One Direction", options: ["נכון", "לא נכון"], answer: "נכון", topic: "music" },
    { type: "multiple_choice", question: "מהו שם האלבום הפורץ של דרייק מ-2013?", options: ["Take Care", "Nothing Was the Same", "Views", "Scorpion"], answer: "Nothing Was the Same", topic: "music" },
    { type: "multiple_choice", question: "אוליביה רודריגו זכתה בגראמי לאמנית החדשה של השנה באיזה טקס?", options: ["2021", "2022", "2023", "2024"], answer: "2022", topic: "music" },
    { type: "open", question: "מהו שם ה-alter ego של ביונסה המוצג בפרויקט הוויזואלי שלה מ-2016?", answer: "Lemonade (לא בדיוק alter ego, האלבום נקרא Lemonade)", topic: "music" },
    { type: "true_false", question: "טיילור סוויפט היא האמנית הראשונה ששברה את שיא הסיבוב העולמי הרווחי ביותר בהיסטוריה", options: ["נכון", "לא נכון"], answer: "נכון", topic: "music" },
    { type: "multiple_choice", question: "מי שרה את 'Unholy' עם קים פטרס?", options: ["Sam Smith", "Ed Sheeran", "Doja Cat", "Lizzo"], answer: "Sam Smith", topic: "music" },
    { type: "multiple_choice", question: "מהו שם האלבום האחרון של טיילור סוויפט שיצא ב-2024?", options: ["Midnights", "Folklore", "The Tortured Poets Department", "Evermore"], answer: "The Tortured Poets Department", topic: "music" },
    { type: "true_false", question: "סברינה קרפנטר הופיעה בסדרת הדיסני 'Girl Meets World'", options: ["נכון", "לא נכון"], answer: "נכון", topic: "music" },
    { type: "open", question: "מהו שמה הדמות שמגלמת אוליביה רודריגו בסדרת הדיסני+ 'High School Musical: The Musical: The Series'?", answer: "ניני סאלאזאר-רוברטס (Nini)", topic: "music" },
    { type: "multiple_choice", question: "מי שרה את 'Thank U, Next'?", options: ["טיילור סוויפט", "אריאנה גראנדה", "בילי אייליש", "דואה ליפה"], answer: "אריאנה גראנדה", topic: "music" },
  ],

  tv: [
    { type: "multiple_choice", question: "מהו שם הממד המקביל בסדרת 'Stranger Things'?", options: ["The Shadow Realm", "The Upside Down", "The Dark Dimension", "The Void"], answer: "The Upside Down", topic: "tv" },
    { type: "multiple_choice", question: "מי מגלמת את 'אחת עשרה' (Eleven) בסדרת Stranger Things?", options: ["Sadie Sink", "Millie Bobby Brown", "Natalia Dyer", "Maya Hawke"], answer: "Millie Bobby Brown", topic: "tv" },
    { type: "open", question: "באיזו עיר קטנה בארה\"ב מתרחשת סדרת 'Stranger Things'?", answer: "הוקינס, אינדיאנה (Hawkins, Indiana)", topic: "tv" },
    { type: "true_false", question: "השיר 'Running Up That Hill' של קייט בוש הפך להיט מחדש בזכות עונה 4 של Stranger Things", options: ["נכון", "לא נכון"], answer: "נכון", topic: "tv" },
    { type: "multiple_choice", question: "מי יצרו את סדרת 'Stranger Things'?", options: ["J.J. Abrams", "ה-Duffer Brothers", "Ryan Murphy", "Shonda Rhimes"], answer: "ה-Duffer Brothers", topic: "tv" },
    { type: "multiple_choice", question: "מהו שם העיירה הבדיונית בסדרת 'Gilmore Girls'?", options: ["Woodbury", "Stars Hollow", "Pinebrook", "Cedar Cove"], answer: "Stars Hollow", topic: "tv" },
    { type: "multiple_choice", question: "מי מגלמת את לורלאי גילמור ב-'Gilmore Girls'?", options: ["Alexis Bledel", "Lauren Graham", "Kelly Bishop", "Melissa McCarthy"], answer: "Lauren Graham", topic: "tv" },
    { type: "true_false", question: "רורי גילמור מתקבלת לאוניברסיטת הרווארד ב-'Gilmore Girls'", options: ["נכון", "לא נכון"], answer: "לא נכון", topic: "tv" },
    { type: "open", question: "מהו שם בית הקפה של לוק ב-'Gilmore Girls'?", answer: "Luke's Diner", topic: "tv" },
    { type: "multiple_choice", question: "מי מגלמת את גלוריה ב-'Modern Family'?", options: ["Julie Bowen", "Sofia Vergara", "Ariel Winter", "Sarah Hyland"], answer: "Sofia Vergara", topic: "tv" },
    { type: "true_false", question: "'Modern Family' רצה 11 עונות", options: ["נכון", "לא נכון"], answer: "נכון", topic: "tv" },
    { type: "multiple_choice", question: "מי מגלמת את 'Wednesday Addams' בסדרת 'Wednesday' של נטפליקס?", options: ["Emma Myers", "Hunter Doohan", "Jenna Ortega", "Joy Sunday"], answer: "Jenna Ortega", topic: "tv" },
    { type: "open", question: "בית הספר שבו לומדת Wednesday Addams בסדרה הוא...", answer: "Nevermore Academy", topic: "tv" },
    { type: "multiple_choice", question: "מהו שם בית הקפה ב-'Friends'?", options: ["The Perk", "Central Perk", "Coffee House", "Java City"], answer: "Central Perk", topic: "tv" },
    { type: "true_false", question: "הסדרה 'Friends' מתרחשת בניו יורק", options: ["נכון", "לא נכון"], answer: "נכון", topic: "tv" },
    { type: "multiple_choice", question: "מי אומר את הביטוי 'How you doin'?' ב-'Friends'?", options: ["Ross", "Chandler", "Joey", "Phoebe"], answer: "Joey", topic: "tv" },
    { type: "multiple_choice", question: "מי מגלמת את קלייר פריצ'ט ב-'Modern Family'?", options: ["Sofia Vergara", "Julie Bowen", "Ariel Winter", "Jessie Tyler Ferguson"], answer: "Julie Bowen", topic: "tv" },
    { type: "true_false", question: "בסדרת Stranger Things, המפלצת הראשונה נקראת 'Demogorgon'", options: ["נכון", "לא נכון"], answer: "נכון", topic: "tv" },
    { type: "multiple_choice", question: "כמה עונות יש לסדרת 'Breaking Bad'?", options: ["4", "5", "6", "7"], answer: "5", topic: "tv" },
    { type: "open", question: "מהו שם הדמות הראשית בסדרת 'Breaking Bad'?", answer: "וולטר ווייט (Walter White)", topic: "tv" },
    { type: "multiple_choice", question: "באיזו פלטפורמה שודרה לראשונה הסדרה 'Wednesday'?", options: ["HBO", "Disney+", "Netflix", "Amazon Prime"], answer: "Netflix", topic: "tv" },
    { type: "true_false", question: "בסדרת 'Game of Thrones' יש 8 עונות", options: ["נכון", "לא נכון"], answer: "נכון", topic: "tv" },
    { type: "multiple_choice", question: "מי מגלמת את מילי בסדרת 'Euphoria'?", options: ["Zendaya", "Sydney Sweeney", "Hunter Schafer", "Alexa Demie"], answer: "Zendaya", topic: "tv" },
  ],

  musicals: [
    { type: "multiple_choice", question: "מי כתב את המחזמר 'Hamilton'?", options: ["Stephen Sondheim", "Lin-Manuel Miranda", "Andrew Lloyd Webber", "Claude-Michel Schönberg"], answer: "Lin-Manuel Miranda", topic: "musicals" },
    { type: "open", question: "על מי מבוסס המחזמר 'Hamilton'?", answer: "על אלכסנדר המילטון, מייסד האמריקאי ומזכיר האוצר הראשון של ארה\"ב", topic: "musicals" },
    { type: "true_false", question: "המחזמר 'Hamilton' משלב מוזיקת היפ-הופ ורפ", options: ["נכון", "לא נכון"], answer: "נכון", topic: "musicals" },
    { type: "multiple_choice", question: "מהו השיר הפותח את המחזמר 'Hamilton'?", options: ["My Shot", "Alexander Hamilton", "Wait for It", "Satisfied"], answer: "Alexander Hamilton", topic: "musicals" },
    { type: "multiple_choice", question: "מי הן שתי הדמויות הראשיות ב-'Wicked'?", options: ["Elphaba ו-Glinda", "Elphaba ו-Dorothy", "Glinda ו-Nessa", "Elphaba ו-Fiyero"], answer: "Elphaba ו-Glinda", topic: "musicals" },
    { type: "open", question: "מהו שמו של שיר הנושא הראשי מ'Wicked' שבו הדמות הראשית מכריזה שהיא לא תיפגע מדעות אחרים?", answer: "Defying Gravity", topic: "musicals" },
    { type: "true_false", question: "המחזמר 'Phantom of the Opera' נכתב על ידי אנדרו לויד ובר", options: ["נכון", "לא נכון"], answer: "נכון", topic: "musicals" },
    { type: "multiple_choice", question: "עד לאחרונה, מהו המחזמר שרץ הכי הרבה זמן בברודווי?", options: ["Chicago", "Hamilton", "The Phantom of the Opera", "Cats"], answer: "The Phantom of the Opera", topic: "musicals" },
    { type: "multiple_choice", question: "מוזיקת איזו להקה מוצגת במחזמר 'Mamma Mia'?", options: ["The Beatles", "Queen", "ABBA", "The Rolling Stones"], answer: "ABBA", topic: "musicals" },
    { type: "true_false", question: "המחזמר 'Les Misérables' מבוסס על רומן של ויקטור הוגו", options: ["נכון", "לא נכון"], answer: "נכון", topic: "musicals" },
    { type: "open", question: "מהו השיר המפורסם מ'Les Misérables' שמגלם חלום לעתיד טוב יותר?", answer: "I Dreamed a Dream", topic: "musicals" },
    { type: "multiple_choice", question: "באיזו עיר מתרחש המחזמר 'Hamilton' בעיקרו?", options: ["בוסטון", "פילדלפיה", "ניו יורק", "וושינגטון"], answer: "ניו יורק", topic: "musicals" },
    { type: "true_false", question: "המחזמר 'The Lion King' מבוסס על סרט הדיסני", options: ["נכון", "לא נכון"], answer: "נכון", topic: "musicals" },
    { type: "multiple_choice", question: "מי כתב את המוזיקה למחזמר 'Cats'?", options: ["Andrew Lloyd Webber", "Stephen Sondheim", "Lin-Manuel Miranda", "Jerry Herman"], answer: "Andrew Lloyd Webber", topic: "musicals" },
    { type: "open", question: "מהו שמו של השיר המפורסם ביותר מ-'Cats' שהפך לסטנדרט בג'אז ובפופ?", answer: "Memory", topic: "musicals" },
    { type: "multiple_choice", question: "מחזמר 'Grease' מתרחש באיזה עשור?", options: ["שנות ה-40", "שנות ה-50", "שנות ה-60", "שנות ה-70"], answer: "שנות ה-50", topic: "musicals" },
    { type: "true_false", question: "הסרט 'Wicked' (2024) בכיכובה של אריאנה גראנדה מבוסס על המחזמר", options: ["נכון", "לא נכון"], answer: "נכון", topic: "musicals" },
    { type: "multiple_choice", question: "מהי שנת הפתיחה של 'Wicked' בברודווי?", options: ["2001", "2003", "2005", "2000"], answer: "2003", topic: "musicals" },
    { type: "open", question: "מי מגלמת את אלפבה בסרט 'Wicked' (2024)?", answer: "סינתיה אריבו (Cynthia Erivo)", topic: "musicals" },
    { type: "multiple_choice", question: "באיזה מחזמר מופיע השיר 'Seasons of Love'?", options: ["Rent", "Hamilton", "Chicago", "Avenue Q"], answer: "Rent", topic: "musicals" },
  ],

  world_history: [
    { type: "multiple_choice", question: "באיזו שנה הסתיימה מלחמת העולם השנייה?", options: ["1943", "1944", "1945", "1946"], answer: "1945", topic: "world_history" },
    { type: "multiple_choice", question: "איזו מדינה הפילה את פצצות האטום על יפן?", options: ["בריטניה", "ברה\"מ", "צרפת", "ארה\"ב"], answer: "ארה\"ב", topic: "world_history" },
    { type: "true_false", question: "חומת ברלין נפלה בשנת 1989", options: ["נכון", "לא נכון"], answer: "נכון", topic: "world_history" },
    { type: "open", question: "מה היה שמה של המבצע שבו נחתו כוחות בעלות הברית בנורמנדי ב-1944?", answer: "מבצע אוברלורד (Operation Overlord) - D-Day", topic: "world_history" },
    { type: "multiple_choice", question: "מתי נחתו בני אדם על הירח לראשונה?", options: ["1967", "1968", "1969", "1970"], answer: "1969", topic: "world_history" },
    { type: "multiple_choice", question: "מי היה האדם הראשון על הירח?", options: ["באז אולדרין", "ניל ארמסטרונג", "ג'ון גלן", "יורי גגרין"], answer: "ניל ארמסטרונג", topic: "world_history" },
    { type: "true_false", question: "מלחמת העולם הראשונה פרצה לאחר רצח הארכידוכס פרנץ פרדיננד", options: ["נכון", "לא נכון"], answer: "נכון", topic: "world_history" },
    { type: "multiple_choice", question: "מתי פרצה המהפכה הצרפתית?", options: ["1776", "1789", "1804", "1815"], answer: "1789", topic: "world_history" },
    { type: "multiple_choice", question: "מי היה הנשיא הדמוקרטי הראשון שנבחר בדרום אפריקה לאחר האפרטהייד?", options: ["דזמונד טוטו", "נלסון מנדלה", "תאבו מבקי", "ויינפריד סיסולו"], answer: "נלסון מנדלה", topic: "world_history" },
    { type: "true_false", question: "ברית המועצות התפרקה בשנת 1991", options: ["נכון", "לא נכון"], answer: "נכון", topic: "world_history" },
    { type: "multiple_choice", question: "מי פיתח את תורת היחסות?", options: ["אייזק ניוטון", "מקס פלאנק", "אלברט איינשטיין", "ניקולה טסלה"], answer: "אלברט איינשטיין", topic: "world_history" },
    { type: "open", question: "כיצד נקראה המגפה שהרגה כשליש מאוכלוסיית אירופה במאה ה-14?", answer: "המוות השחור (The Black Death) / מגפת הדבר", topic: "world_history" },
    { type: "multiple_choice", question: "מי היה הנשיא האמריקאי הראשון?", options: ["אברהם לינקולן", "בנג'מין פרנקלין", "ג'ורג' וושינגטון", "תומס ג'פרסון"], answer: "ג'ורג' וושינגטון", topic: "world_history" },
    { type: "true_false", question: "האו\"ם נוסד לאחר מלחמת העולם השנייה", options: ["נכון", "לא נכון"], answer: "נכון", topic: "world_history" },
    { type: "multiple_choice", question: "באיזו שנה הסתיימה מלחמת העולם הראשונה?", options: ["1916", "1917", "1918", "1919"], answer: "1918", topic: "world_history" },
    { type: "open", question: "מי היה מנהיג גרמניה הנאצית?", answer: "אדולף היטלר", topic: "world_history" },
    { type: "multiple_choice", question: "ב-1492 כריסטופר קולומבוס הגיע ל...", options: ["הודו", "אפריקה", "אמריקה", "אסיה"], answer: "אמריקה", topic: "world_history" },
    { type: "true_false", question: "המלחמה הקרה הייתה עימות צבאי ישיר בין ארה\"ב לברה\"מ", options: ["נכון", "לא נכון"], answer: "לא נכון", topic: "world_history" },
    { type: "multiple_choice", question: "באיזה אירוע פתחה יפן את מלחמת העולם השנייה בפרל הארבור?", options: ["1939", "1940", "1941", "1942"], answer: "1941", topic: "world_history" },
    { type: "open", question: "מהו שם ההסכם שסיים את מלחמת העולם הראשונה ב-1919?", answer: "אמנת ורסאי (Treaty of Versailles)", topic: "world_history" },
    { type: "multiple_choice", question: "מי היה מנהיג הברה\"מ בתקופת משבר הטילים הקובני?", options: ["סטאלין", "בריז'נייב", "חרושצ'וב", "גורבצ'וב"], answer: "חרושצ'וב", topic: "world_history" },
  ],

  israel_history: [
    { type: "multiple_choice", question: "מתי הוכרזה הקמת מדינת ישראל?", options: ["14 במאי 1947", "14 במאי 1948", "29 בנובמבר 1947", "15 במאי 1948"], answer: "14 במאי 1948", topic: "israel_history" },
    { type: "multiple_choice", question: "מי הכריז על הקמת מדינת ישראל?", options: ["חיים וייצמן", "דוד בן-גוריון", "מנחם בגין", "משה שרת"], answer: "דוד בן-גוריון", topic: "israel_history" },
    { type: "multiple_choice", question: "מי היה ראש הממשלה הראשון של מדינת ישראל?", options: ["חיים וייצמן", "לוי אשכול", "דוד בן-גוריון", "משה שרת"], answer: "דוד בן-גוריון", topic: "israel_history" },
    { type: "multiple_choice", question: "באיזו שנה התרחשה מלחמת ששת הימים?", options: ["1956", "1967", "1973", "1948"], answer: "1967", topic: "israel_history" },
    { type: "multiple_choice", question: "באיזו שנה התרחשה מלחמת יום הכיפורים?", options: ["1967", "1970", "1973", "1976"], answer: "1973", topic: "israel_history" },
    { type: "true_false", question: "ישראל ניצחה במלחמת ששת הימים תוך שישה ימים", options: ["נכון", "לא נכון"], answer: "נכון", topic: "israel_history" },
    { type: "open", question: "כיצד נקראה מלחמת 1948 שבה נלחמה ישראל נגד מדינות ערב?", answer: "מלחמת העצמאות", topic: "israel_history" },
    { type: "multiple_choice", question: "באיזו שנה נחתמו הסכמי אוסלו?", options: ["1991", "1993", "1995", "1997"], answer: "1993", topic: "israel_history" },
    { type: "multiple_choice", question: "מי חתם על הסכמי אוסלו מטעם ישראל?", options: ["שמעון פרס", "יצחק שמיר", "יצחק רבין", "אהוד ברק"], answer: "יצחק רבין", topic: "israel_history" },
    { type: "true_false", question: "יצחק רבין נרצח בשנת 1995", options: ["נכון", "לא נכון"], answer: "נכון", topic: "israel_history" },
    { type: "multiple_choice", question: "מהו שם הפרלמנט הישראלי?", options: ["הסנאט", "הכנסת", "הפרלמנט", "המועצה"], answer: "הכנסת", topic: "israel_history" },
    { type: "multiple_choice", question: "כמה חברי כנסת יש?", options: ["100", "110", "120", "130"], answer: "120", topic: "israel_history" },
    { type: "multiple_choice", question: "מי הייתה ראש הממשלה של ישראל בזמן מלחמת יום הכיפורים?", options: ["גולדה מאיר", "לוי אשכול", "מנחם בגין", "ישראל גלילי"], answer: "גולדה מאיר", topic: "israel_history" },
    { type: "true_false", question: "מבצע אנטבה (1976) היה מבצע להצלת חטופים ישראלים באוגנדה", options: ["נכון", "לא נכון"], answer: "נכון", topic: "israel_history" },
    { type: "multiple_choice", question: "עם אילו מדינות חתמה ישראל על הסכמי אברהם ב-2020?", options: ["מצרים וירדן", "איחוד האמירויות ובחריין", "ערב הסעודית ועומאן", "מרוקו ותוניסיה"], answer: "איחוד האמירויות ובחריין", topic: "israel_history" },
    { type: "multiple_choice", question: "מתי חתמה ישראל על הסכם שלום עם מצרים?", options: ["1977", "1978", "1979", "1980"], answer: "1979", topic: "israel_history" },
    { type: "open", question: "מי היה נשיא מצרים שחתם על הסכם השלום עם ישראל ב-1979?", answer: "אנואר סאדאת (Anwar Sadat)", topic: "israel_history" },
    { type: "true_false", question: "ישראל חתמה על הסכם שלום עם ירדן בשנת 1994", options: ["נכון", "לא נכון"], answer: "נכון", topic: "israel_history" },
    { type: "multiple_choice", question: "מי היה ראש הממשלה שהחליט על נסיגה מרצועת עזה ב-2005?", options: ["אהוד ברק", "אהוד אולמרט", "אריאל שרון", "בנימין נתניהו"], answer: "אריאל שרון", topic: "israel_history" },
    { type: "open", question: "מה קרה ב-7 באוקטובר 2023?", answer: "תקיפת חמאס על ישראל - פיגוע הטבח הגדול ביותר על יהודים מאז השואה, שהוביל למלחמת חרבות ברזל", topic: "israel_history" },
    { type: "multiple_choice", question: "מי היה ראש הממשלה הראשון מהימין שנבחר בישראל?", options: ["אריאל שרון", "יצחק שמיר", "מנחם בגין", "אהוד אולמרט"], answer: "מנחם בגין", topic: "israel_history" },
  ],
};
